# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

# I DON'T KNOW HOW ANY OF THIS WORKS HELP

name: build
on: [push]

jobs:
  setup:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: setup jdk 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'microsoft'

      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
  build-1-20:
    runs-on: ubuntu-22.04
    steps:
      - name: build
        run: |
          ./gradlew :1.20:build
  build-1-20-2:
    runs-on: ubuntu-22.04
    steps:
      - name: build
        run: |
          ./gradlew :1.20.2:build
  build-1-20-3:
    runs-on: ubuntu-22.04
    steps:
      - name: build
        run: |
          ./gradlew :1.20.3:build
  build-1-20-5:
    runs-on: ubuntu-22.04
    steps:
      - name: build
        run: |
          ./gradlew :1.20.5:build
  build-1-21:
    runs-on: ubuntu-22.04
    steps:
      - name: build
        run: |
          ./gradlew :1.21:build
  build-1-21-2:
    runs-on: ubuntu-22.04
    steps:
      - name: build
        run: |
          ./gradlew :1.21.2:build
  build-1-21-4:
    runs-on: ubuntu-22.04
    steps:
      - name: build
        run: |
          ./gradlew :1.21.4:build
  build-1-21-5:
    runs-on: ubuntu-22.04
    steps:
      - name: build
        run: |
          ./gradlew :1.21.5:build
  build-1-21-6:
    runs-on: ubuntu-22.04
    steps:
      - name: build
        run: |
          ./gradlew :1.21.6:build
  build-1-21-9:
    runs-on: ubuntu-22.04
    steps:
      - name: build
        run: |
          ./gradlew :1.21.9:build